# Generated by Django 3.2.9 on 2024-06-04 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_ticket_image_alt_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='image_alt_text',
        ),
    ]
