# Generated by Django 3.2.9 on 2024-06-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_ticket_image_alt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='image_alt_text',
            field=models.CharField(blank=True, help_text="Texte alternatif pour l'image", max_length=255),
        ),
    ]
