# Generated by Django 5.0.4 on 2024-04-26 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_alter_user_managers_remove_user_follows"),
        ("blog", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserFollows",
        ),
    ]
