# Generated by Django 5.0.4 on 2024-04-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_profile_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile_photo",
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
