# Generated by Django 4.2 on 2024-04-27 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_initial"),
        ("authentication", "0005_alter_user_managers_remove_user_follows"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="follows",
            field=models.ManyToManyField(
                related_name="followers",
                through="blog.UserFollows",
                to=settings.AUTH_USER_MODEL,
                verbose_name="suit",
            ),
        ),
    ]
